FROM apache/airflow:2.9.1

USER root
RUN apt-get update && apt-get install -y git libpq-dev && apt-get clean

USER airflow
RUN pip install --no-cache-dir psycopg2-binary && \
    pip install --no-cache-dir \
    "dbt-core==1.8.0" \
    "dbt-postgres==1.8.0" \
    --no-deps && \
    pip install --no-cache-dir \
    "dbt-adapters>=0.1.0a2,<2.0" \
    "dbt-common>=1.0.2,<2.0" \
    "dbt-semantic-interfaces>=0.5.1,<0.6" \
    requests \
    pandas \
    sqlalchemy