FROM apache/airflow:2.9.1

USER root
RUN apt-get update && apt-get install -y git libpq-dev gcc && apt-get clean

USER airflow
RUN python -m venv /home/airflow/dbt-env && \
    /home/airflow/dbt-env/bin/pip install --upgrade pip && \
    /home/airflow/dbt-env/bin/pip install \
    psycopg2-binary \
    dbt-core==1.8.0 \
    dbt-postgres==1.8.0