apiVersion: 1

contactPoints:
  - orgId: 1
    name: webhook-clase
    receivers:
      - uid: webhook-clase-receiver
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://webhook-receiver:8080/grafana-alerts
          httpMethod: POST
